config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # devise_scope :user do
  #   get "profile_edit", to: "users/registrations#profile_edit", as: "profile_edit"
  #   patch "profile_update", to: "users/registrations#profile_update", as: "profile_update"
  # end

  root 'home#top'
  get 'home/about', to: 'home#about'
  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  get "user/:id/likes", to: "users#likes", as: "user_likes"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :sns_credentials
  
  validates :name,  presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  
  def posts
    return Post.where(user_id: self.id)
  end
  
  # THUMBNAIL_SIZE = [60, 60]
  mount_uploader :image_name, ImageUploader

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email:    auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else #ユーザー情報が未登録なので、新規登録画面へ遷移する
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create], if: :devise_controller?
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end


  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # def update_resource(resource, params)
  #   resource.update_without_password(params)
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   flash[:notice] = "サインアップに成功しました"
  #   user_path(resource)
  # end

  def after_update_path_for(resource)
    user_path
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to user_path
    else
      render :edit
    end
  end

  def likes
    @user = User.find_by(id: params[:id])
  end

  def ensure_correct_user
    if current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to posts_path
    end
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :image_name, :password)
    end

  # protected

  #   def update_resource(resource, params)
  #     resource.update_without_password(params)
  #   end

  # 効いていないのでコメントアウトしてる
  # def after_update_path_for(resource)
  #   user_path
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% if current_user.errors.any? %>
  <div class="flash">
    <%= current_user.errors.full_messages %>
  </div>
<% end %>
<div class="main users-edit">
  <div class="container">
    <h1 class="form-heading">ユーザー登録編集</h1>
    <%= form_with model: @user, url: user_path, local: true do |f| %>
    <%# <%= form_with model: @user, url: user_path, html: { method: :put}, local: true do |f| %>
      <div class="form users-form">
        <div class="form-body">
          <%= f.label "ユーザー名" %>
          <%= f.text_field :name, placeholder: "名前を入力してください" %>
          
          <%= f.label "アイコン", class: 'image_label' %>
          <%= image_tag @user.image_name.to_s, alt: "preview", class: "prev-image" %>
          <%= f.file_field :image_name, class: "image_form" %>
          <%# <%= f.hidden_field :image_cache %>

          <%= f.label "メールアドレス" %>
          <%= f.text_field :email, placeholder: "emailを入力してください" %>
          
          <%= f.label "パスワード" %>
          <%= f.password_field :password, placeholder: "登録しているパスワードを入力してください" %>

          <%= f.submit "更新"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">ユーザー一覧</h1>
    <% @users.each do |user|%>
      <div class="users-index-item">
        <div class="user-left">
          <%= image_tag user.image_name.to_s %>
        </div>
        <div class="user-right">
          <%= link_to user.name, user_path(user) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/likes.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <%= image_tag @user.image_name.to_s %>
      <h2> <%= @user.name %> </h2>
      <p> <%= @user.email %> </p>
      <% if @user.id == current_user.id %>
        <%= link_to "編集", edit_user_path(current_user) %>
      <% end %>
    </div>

    <ul class="user-tabs">
      <li> <%= link_to "投稿", user_path(@user) %> </li>
      <li class="active"> <%= link_to "いいね！", user_likes_path(@user) %> </li>
    </ul>
    
    <% @user.liked_posts.each do |post| %>
      <div class="posts-index-item">
        <div class="post-left">
          <%= image_tag post.user.image_name.to_s %>
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to post.user.name, user_path(post.user.id) %>
          </div>
            <%= link_to post.content, post_path(post.id) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <%= image_tag @user.image_name.to_s %>
      <h2> <%= @user.name %> </h2>
      <p> <%= @user.email %> </p>
      <% if @user.id == current_user.id %>
        <%= link_to "編集", edit_user_path(current_user) %>
      <% end %>
    </div>

    <ul class="user-tabs">
      <li class="active"> <%= link_to "投稿", user_path(@user) %> </li>
      <li> <%= link_to "いいね！", user_likes_path(@user) %> </li>
    </ul>
    
    <% @user.posts.each do |post| %>
      <div class="posts-index-item">
        <div class="post-left">
          <%= image_tag post.user.image_name.to_s %>
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to post.user.name, user_path(post.user.id) %>
          </div>
            <%= link_to post.content, post_path(post.id) %>
        </div>
      </div>
    <% end %>
  </div>
</div>