config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # devise_scope :user do
  #   get "profile_edit", to: "users/registrations#profile_edit", as: "profile_edit"
  #   patch "profile_update", to: "users/registrations#profile_update", as: "profile_update"
  # end

  root 'home#top'
  get 'home/about', to: 'home#about'
  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  get "user/:id/likes", to: "users#likes", as: "user_likes"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  validates :content, presence: true, length: {maximum: 140}
  validates :user_id, presence: true

  def user
    return User.find_by(id: self.user_id)
  end

  # THUMBNAIL_SIZE = [400, 400]
  mount_uploader :image, ImageUploader

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find_by(id: params[:id])
    @user = User.find_by(id: @post.user_id)
    @like = Like.new
    @like_count = Like.where(post_id: @post.id).count
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "投稿を作成しました"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿を編集しました"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to posts_path
  end

  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @post.user.id != current_user.id
      flash[:notice] = "権限がありません"
      redirect_to posts_path
    end
  end

  private
    def post_params
      params.required(:post).permit(:content, :image).merge(user_id: current_user.id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="main post-new">
  <div class="container">
    <h1 class="form-heading">編集する</h1>
      <%= form_with model: @post, url: post_path, local: true do |f| %>
        <div class="form">
          <div class="form-body">
            <% @post.errors.full_messages.each do |message| %>
              <div class="form-error">
                <%= message %>
              </div>
            <% end %>
            <%= f.text_area :content %>
            <%= f.submit "保存" %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <div class="post-left">
          <%= image_tag post.user.image_name.to_s %>
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to post.user.name, user_path(post.user.id) %>
          </div>
          <%= link_to post.content, post_path(post.id) %>
          <br>
          <span class="fa fa-heart like-btn-unlike "> <%= post.liked_users.count %> </span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main post-new">
  <div class="container">
    <h1 class="form-heading">投稿する</h1>
      <%= form_with model: @post, url: posts_path, local: true do |f| %>
        <div class="form">
          <div class="form-body">
            <% @post.errors.full_messages.each do |message| %>
              <div class="form-error">
                <%= message %>
              </div>
            <% end %>
            
            <%= f.label :content %>
            <%= f.text_area :content %>

            <%= f.label :image %>
            <%= f.file_field :image %>

            <%= f.submit "投稿" %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <div class="post-user-name">
        <%= image_tag @user.image_name.to_s %>
        <%= link_to @user.name, user_path(@user) %>
      </div>
      <p><%= @post.content %></p>
      <% if @post.image %>
        <div class="posts-show-item-image">
          <%= image_tag @post.image.to_s %>
        </div>
      <% end %>
      <div class="post-time">
        <%= @post.created_at %>
      </div>

      <% if Like.find_by(user_id: current_user.id, post_id: @post.id) %>
        <%= link_to post_like_path(@post), method: :delete do %> 
          <span class="fa fa-heart like-btn-unlike">
        <% end %>
      <% else %>
        <%= link_to post_likes_path(@post), method: :post do %>
          <span class="fa fa-heart like-btn">
        <% end %>
      <% end %>
      <%= @like_count %>

      <% if @post.user.id == current_user.id %>
        <div class="post-menus">
          <%= link_to "編集", edit_post_path(@post) %>
          <%= link_to "削除", post_path(@post), method: :delete %>
        </div>
      <% end %>
    </div>
  </div>
</div>