config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # devise_scope :user do
  #   get "profile_edit", to: "users/registrations#profile_edit", as: "profile_edit"
  #   patch "profile_update", to: "users/registrations#profile_update", as: "profile_update"
  # end

  root 'home#top'
  get 'home/about', to: 'home#about'
  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  get "user/:id/likes", to: "users#likes", as: "user_likes"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <header>
      <div class="header-logo">
        <% if user_signed_in? %>
          <%= link_to "TweetApp", posts_path %>
        <% else %>
          <%= link_to "TweetApp", root_path %>
        <% end %>
      </div>
      <ul class="header-menus">
        <% if user_signed_in? %>
          <li><%= link_to current_user.name, edit_user_path(current_user) %></li>
          <li><%= link_to "投稿一覧", posts_path %></li>
          <li><%= link_to "新規投稿", new_post_path %></li>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "TweetAppとは", home_about_path %></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </header>

    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>

    <%= yield %>
  </body>
</html>